name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: Ruby ${{ matrix.ruby }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        ruby:
          - '3.2.9'
          - '3.3.10'
          - '3.4.7'

    steps:
      - name: Install libvips (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        env:
          DEBIAN_FRONTEND: noninteractive
        run: sudo apt-get install --fix-missing -qq -o Acquire::Retries=3 libvips
      - name: Install libvips (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install vips
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: ${{ matrix.os != 'windows-latest' }}
      - name: Run the default task
        run: bundle exec rake
